### ISSUE TITLE
hydration failing for functions that do no have node_modules

### ISSUE THREAD

**Issue by brianleroux** [architect/hydrate#26]
Suggested fix:

- ensure node_modules/@architect/data exists
- ensure (mkdirp) node_modules/@architect/shared exists
- do not run this code if a project is 6.x or higher

Culprit is here:

https://github.com/architect/hydrate/blob/master/src/shared/copy-arc.js#L64

Error here:

```
#! arc sandbox
         app ⌁ hello-world
      region ⌁ us-east-1
     profile ⌁ smallwins
     version ⌁ Architect CLI 6.0.0-RC.2
         cwd ⌁ /Users/brianleroux/Repo/mike

✓ Found Architect manifest, starting up
✓ Found new functions to hydrate!
⚬ Hydrating dependencies: /src/http/get-hellos [npm ci]
added 0 packages in 0.02s

fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'src/http/get-hellos/node_modules/@architect/shared/.arc'
    at Object.openSync (fs.js:438:3)
    at Object.writeFileSync (fs.js:1189:35)
    at copy (/Users/brianleroux/Repo/architect/node_modules/@architect/hydrate/src/shared/copy-arc.js:64:8)
    at Array.copier (/Users/brianleroux/Repo/architect/node_modules/@architect/hydrate/src/shared/copy-arc.js:24:9)
    at each (/Users/brianleroux/Repo/architect/node_modules/run-series/index.js:19:24)
    at copy (/Users/brianleroux/Repo/architect/node_modules/@architect/hydrate/src/shared/copy-arc.js:65:5)
    at Array.copier (/Users/brianleroux/Repo/architect/node_modules/@architect/hydrate/src/shared/copy-arc.js:24:9)
    at runSeries (/Users/brianleroux/Repo/architect/node_modules/run-series/index.js:22:33)
    at gotBasePaths (/Users/brianleroux/Repo/architect/node_modules/@architect/hydrate/src/shared/copy-arc.js:22:5)
```

**Comment by ryanblock** [comment]
Steps to reproduce are not present, but I think this is now resolved?
